version: "3"

services:
  auth-backend:
    build: ./auth-backend
    image: gleb/datomatica-express-auth
    container_name: express-auth
    ports:
      - "5000:5000"
    volumes:
      - "./:/usr/src/express-auth"
    command: node app.js
    environment:
      - DATABASE_URL=postgresql+psycopg2://gleb@docker.for.mac.host.internal/gleb
      - NODE_ENV=development
      - FETCHER_URL=http://falcon-fetcher:8001/
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      
    networks:
      - backend

  falcon-fetcher:
    build: ./falcon-fetcher
    image: gleb/datomatica-falcon-fetcher
    container_name: falcon-fetcher
    volumes:
      - './:/usr/src/falcon-fetcher'
    command: gunicorn -b 0.0.0.0:8001 server.app:falcon_app
    environment:
      - DOCKER_ENV=True
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
      - DB_HOST=docker.for.mac.host.internal
      - DATABASE_URL=postgresql+psycopg2://gleb@docker.for.mac.host.internal/gleb
      - MODEL_URL=http://falcon-model:8000/
    
    depends_on:
      - auth-backend
      - redis

    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    networks:
      - backend
  celery:
    image: gleb/datomatica-falcon-fetcher
    volumes:
      - './:/usr/src/falcon-fetcher'
      - './logs:/usr/src/falcon-fetcher/logs'
    command: celery -A server.celery_app worker --autoscale=16,3 --loglevel=debug
    environment:
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
      - DB_HOST=docker.for.mac.host.internal
      - DATABASE_URL=postgresql+psycopg2://gleb@docker.for.mac.host.internal/gleb
    depends_on:
      - falcon-fetcher
      - redis
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

    networks:
      - backend

  falcon-model:
    restart: always 
    build: ./falcon-model
    image: gleb/datomatica-falcon-model
    container_name: falcon-model
    ports:
      - '8000:8000'
    volumes:
      - './:/usr/src/falcon-model'
    command: gunicorn -b 0.0.0.0:8000 server.app:falcon_app --access-logfile ./server/logs/access.log
    environment:
      - DATABASE_URL=postgresql+psycopg2://gleb@docker.for.mac.host.internal/gleb
    depends_on:
      - auth-backend
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    networks:
      - backend

  redis:
    image: redis:5.0
    networks:
      - backend


networks:
  backend:
    driver: "bridge"